backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "src/includes/assets/img" # Media files will be stored in the repo under images/uploads
public_folder: "includes/assets/img"

site_url: https://abejunko.jp

collections:
  # Our blog posts
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "記事" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "date" }
      - { label: "Début (pour la page d’accueil)", name: "debut", widget: "text" }
      - { label: "Catégories", name: "tags", widget: "list", required: false }
      - { label: "Corps de l’article", name: "body", widget: "markdown" }
